# Trie des données pour récupération des Visages et des Mots

author = Alexandre Coumes

Trier les databases pour obtenir les ID des images de nos participants.

In [25]:
import pandas as pd

## Faces

### Loading of our data

Here we aim for the right sheet (Main Dataset) and create our subset

In [26]:
df = pd.read_excel("dataset.xlsx", sheet_name=1, header=7)
df.head()

,Model,EthnicitySelf,GenderSelf,AgeSelf,AgeRated,Unnamed: 5,FemaleProb,MaleProb,AsianProb,ChineseAsianProb,...,EyeSize,UpperHeadLength,MidfaceLength,ChinLength,ForeheadHeight,CheekboneHeight,CheekboneProminence,FaceRoundness,fWHR2,RaterN
0,NaN,NaN,NaN,NaN,R002_mean,R002_sd,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AF-200,A,F,NaN,32.571429,NaN,1.000000,0.000000,1.000000,NaN,...,0.060924,0.414099,0.326797,0.130719,0.264706,0.388189,91.5,0.545752,1.973890,28.0
2,AF-201,A,F,NaN,23.666667,NaN,1.000000,0.000000,0.962963,NaN,...,0.041892,0.414414,0.329279,0.144595,0.300901,0.383784,146.0,0.488288,2.068681,27.0
3,AF-202,A,F,NaN,24.448276,NaN,0.827586,0.172414,0.310345,NaN,...,0.051586,0.411080,0.310317,0.173424,0.298475,0.397029,58.0,0.481333,1.987261,29.0
4,AF-203,A,F,NaN,22.758621,NaN,1.000000,0.000000,0.758621,NaN,...,0.063913,0.354407,0.343793,0.169820,0.272266,0.421089,87.5,0.500231,1.902284,29.0

In [27]:
print(df.columns.tolist())

['Model', 'EthnicitySelf', 'GenderSelf', 'AgeSelf', 'AgeRated', 'Unnamed: 5', 'FemaleProb', 'MaleProb', 'AsianProb', 'ChineseAsianProb', 'JapaneseAsianProb', 'IndianAsianProb', 'OtherAsianProb', 'MiddleEasternProb', 'BlackProb', 'LatinoProb', 'MultiProb', 'OtherProb', 'WhiteProb', 'Afraid', 'Unnamed: 20', 'Angry', 'Unnamed: 22', 'Attractive', 'Unnamed: 24', 'Babyfaced', 'Unnamed: 26', 'Disgusted', 'Unnamed: 28', 'Dominant', 'Unnamed: 30', 'Feminine', 'Unnamed: 32', 'Happy', 'Unnamed: 34', 'Masculine', 'Unnamed: 36', 'Prototypic', 'Unnamed: 38', 'Sad', 'Unnamed: 40', 'Suitability', 'Unnamed: 42', 'Surprised', 'Unnamed: 44', 'Threatening', 'Unnamed: 46', 'Trustworthy', 'Unnamed: 48', 'Unusual', 'Unnamed: 50', 'Warm', 'Unnamed: 52', 'Competent', 'Unnamed: 54', 'SocialStatus', 'Unnamed: 56', 'LuminanceMedian', 'NoseWidth', 'NoseLength', 'LipThickness', 'FaceLength', 'EyeHeightR', 'EyeHeightL', 'EyeHeightAvg', 'EyeWidthR', 'EyeWidthL', 'EyeWidthAvg', 'FaceWidthCheeks', 'FaceWidthMouth', 'FaceWidthBZ', 'Forehead', 'UpperFaceLength2', 'PupilTopR', 'PupilTopL', 'PupilTopAsymmetry', 'PupilLipR', 'PupilLipL', 'PupilLipAvg', 'PupilLipAsymmetry', 'EyeDistance', 'BottomLipChin', 'MidcheekChinR', 'MidcheekChinL', 'CheeksAvg', 'MidbrowHairlineR', 'MidbrowHairlineL', 'MidbrowHairlineAvg', 'FaceColorRed', 'FaceColorGreen', 'FaceColorBlue', 'HairColorRed', 'HairColorGreen', 'HairColorBlue', 'HairLuminance', 'EyeLuminanceR', 'EyeLuminanceL', 'EyeBrowThicknessR', 'EyeBrowThicknessL', 'EyeBrowThicknessAvg', 'EyeLidThicknessR', 'EyeLidThicknessL', 'EyeLidThicknessAvg', 'FaceShape', 'Heartshapeness', 'NoseShape', 'LipFullness', 'EyeShape', 'EyeSize', 'UpperHeadLength', 'MidfaceLength', 'ChinLength', 'ForeheadHeight', 'CheekboneHeight', 'CheekboneProminence', 'FaceRoundness', 'fWHR2', 'RaterN']

In [32]:
df['Attractive'] = pd.to_numeric(df['Attractive'], errors='coerce')
df_attractivness = df.dropna(subset=['Attractive']) 
df_attractivness = df_attractivness.sort_values("Attractive", ascending=False)
df_attractivness.head()

,Model,EthnicitySelf,GenderSelf,AgeSelf,AgeRated,Unnamed: 5,FemaleProb,MaleProb,AsianProb,ChineseAsianProb,...,EyeSize,UpperHeadLength,MidfaceLength,ChinLength,ForeheadHeight,CheekboneHeight,CheekboneProminence,FaceRoundness,fWHR2,RaterN
485,WF-233,W,F,NaN,22.608696,NaN,1.0,0.0,0.000000,NaN,...,0.054667,0.413570,0.312014,0.163354,0.322602,0.367545,119.500000,0.378997,1.828704,23.0
198,BF-240,B,F,NaN,24.413793,NaN,1.0,0.0,0.000000,NaN,...,0.052414,0.368421,0.315355,0.144411,0.303828,0.379513,144.500000,0.438452,1.928230,29.0
356,LF-249,L,F,NaN,28.517241,NaN,1.0,0.0,0.068966,NaN,...,0.051197,0.402147,0.315235,0.165153,0.317300,0.378406,128.000000,0.417424,1.849013,29.0
191,BF-233,B,F,NaN,28.692308,NaN,1.0,0.0,0.000000,NaN,...,0.049060,0.387572,0.313369,0.152085,0.289657,0.388389,133.000000,0.415781,1.802247,26.0
435,WF-022,W,F,NaN,19.913978,NaN,1.0,0.0,0.000000,NaN,...,0.053637,0.372007,0.328729,0.180479,0.300875,0.432551,0.104972,0.538214,1.884346,92.0

> We create our Dataset of 60 faces, 30 of the most attractive and the less attractive.

In [33]:
df_attractivness = df_attractivness[['Model', 'Attractive', 'GenderSelf']]
df_top = df_attractivness.head(30)
df_bot = df_attractivness.tail(30)
df_final = pd.concat([df_top, df_bot])
df_final

      Model  Attractive GenderSelf
485  WF-233    5.478261          F
198  BF-240    5.310345          F
356  LF-249    5.241379          F
191  BF-233    5.120000          F
435  WF-022    5.086957          F
176  BF-218    5.080000          F
386  LM-224    5.071429          M
43   AF-242    4.964286          F
174  BF-216    4.892857          F
111  BF-002    4.892473          F
417  WF-003    4.890110          F
250  BM-043    4.852273          M
172  BF-214    4.846154          F
457  WF-205    4.826087          F
199  BF-241    4.821429          F
490  WF-238    4.800000          F
56   AF-255    4.800000          F
122  BF-013    4.777778          F
350  LF-243    4.769231          F
472  WF-220    4.758621          F
437  WF-024    4.755319          F
494  WF-242    4.750000          F
202  BF-244    4.750000          F
187  BF-229    4.730769          F
175  BF-217    4.714286          F
440  WF-027    4.685393          F
19   AF-218    4.678571          F
190  BF-232    4.666667          F
45   AF-244    4.666667          F
425  WF-012    4.663158          F
136  BF-029    2.116279          F
273  BM-219    2.111111          M
185  BF-227    2.111111          F
456  WF-204    2.107143          F
151  BF-044    2.106383          F
366  LM-203    2.090909          M
267  BM-213    2.080000          M
412  LM-251    2.080000          M
576  WM-236    2.038462          M
182  BF-224    2.034483          F
423  WF-010    2.011765          F
500  WF-248    2.000000          F
327  LF-220    2.000000          F
556  WM-215    1.892857          M
145  BF-038    1.892473          F
568  WM-228    1.888889          M
462  WF-210    1.884615          F
89   AM-233    1.857143          M
69   AM-212    1.846154          M
82   AM-226    1.809524          M
547  WM-206    1.806452          M
371  LM-209    1.785714          M
116  BF-007    1.769231          F
542  WM-201    1.727273          M
439  WF-026    1.721649          F
502  WF-250    1.720000          F
416  WF-002    1.612903          F
158  BF-200    1.551724          F
402  LM-240    1.541667          M
80   AM-224    1.520000          M

## Words

In [ ]:
df_word = pd.read_excel("dataset_words.xlsx")
df_word.sort_values(" MeanVal", ascending=True)
df_word_top = df_word.head(30); df_word_bot = df_word.tail(30)
df_word_final = pd.concat([df_word_top, df_word_bot])

In [36]:
df_word_final

,Trait,Translation,FreqMovies,FreqBooks,MeanVal,SDVal,RateVal,MeanPCONS,SDPCONS,RatePCONS,...,RateDisgust,MeanHappinessjoie,SDHappiness,RateHappiness,MeanFear,SDFear,RateFear,MeanSadness,SDSadness,RateSadness
0,accessible,approachable,1.49,4.12,1.443038,1.094823,0.9875,4.191011,1.608757,1.000000,...,1.000000,2.860759,2.055226,1.000000,1.253165,0.759020,1.000000,1.051282,0.222000,0.987342
1,accueillant,welcoming,1.21,1.82,2.137500,0.807304,1,4.191011,1.724663,1.000000,...,1.000000,4.873418,1.814239,1.000000,1.113924,0.480047,1.000000,1.025316,0.158088,1.000000
2,actif,active,4.12,3.58,1.900000,0.82062,1,5.000000,1.644550,1.000000,...,1.000000,3.594937,2.060116,1.000000,1.265823,0.728695,1.000000,1.139241,0.614654,1.000000
3,admirable,admirable,6.02,23.92,2.187500,0.994844,1,4.483146,1.834718,1.000000,...,1.000000,4.379747,2.114079,1.000000,1.164557,0.649070,1.000000,1.063291,0.333658,1.000000
4,admiratif,appreciative,0.26,2.57,0.800000,1.173548,1,4.876404,1.643308,1.000000,...,1.000000,3.582278,2.029321,1.000000,1.291139,0.907969,1.000000,1.202532,0.806699,1.000000
5,adorable,adorable,23.00,6.28,2.137500,0.937864,1,4.303371,1.817869,1.000000,...,1.000000,5.012658,1.891233,1.000000,1.151899,0.556744,1.000000,1.063291,0.403249,1.000000
6,adroit,dexterous,1.13,3.51,1.800000,0.905678,1,4.831461,1.618332,1.000000,...,1.000000,3.012658,2.121282,1.000000,1.189873,0.621742,1.000000,1.050633,0.272629,1.000000
7,adulte,adult,8.02,8.18,1.262500,1.17725,1,4.842697,1.864128,1.000000,...,1.000000,2.848101,2.082212,1.000000,2.240506,1.875723,1.000000,1.759494,1.407081,1.000000
8,affectueux,affectionate,3.56,7.97,1.800000,0.905678,1,4.314607,1.868370,1.000000,...,1.000000,4.898734,1.925503,1.000000,1.341772,1.108083,1.000000,1.329114,1.162684,1.000000
9,affirmatif,assertive,4.82,1.35,0.950000,1.112643,1,4.191011,1.731240,1.000000,...,1.000000,2.063291,1.651276,1.000000,1.379747,0.937862,1.000000,1.113924,0.423276,1.000000
10,agréable,pleasant,37.71,31.35,2.062500,0.752107,1,4.426966,1.814635,1.000000,...,1.000000,5.037975,2.009229,1.000000,1.101266,0.469450,1.000000,1.037975,0.250284,1.000000
11,agressif,aggressive,5.76,6.82,-2.101266,1.032733,0.9875,5.617978,1.301272,1.000000,...,1.000000,1.151899,0.785911,1.000000,4.076923,2.345314,0.987342,2.794872,2.229431,0.987342
12,aidant,caregiver,1.70,11.49,1.862500,0.867759,1,4.584270,1.608281,1.000000,...,0.987342,3.923077,2.106078,0.987342,1.256410,0.889125,0.987342,1.230769,0.836242,0.987342
13,aigri,resentful,0.79,0.54,-1.950000,0.979537,1,5.280899,1.453747,1.000000,...,1.000000,1.202532,0.822438,1.000000,2.607595,2.084237,1.000000,3.670886,2.368173,1.000000
14,aimable,kind,21.98,24.59,1.850000,0.969144,1,4.528090,1.828374,1.000000,...,1.000000,4.468354,1.866269,1.000000,1.126582,0.757308,1.000000,1.139241,0.614654,1.000000
15,alerte,alert,8.05,6.55,0.600000,1.142948,1,4.659091,1.632193,0.988764,...,1.000000,1.632911,1.350947,1.000000,3.430380,2.405568,1.000000,1.797468,1.689938,1.000000
16,altruiste,altruistic,0.52,0.00,1.912500,1.323533,1,4.831461,1.589997,1.000000,...,1.000000,3.569620,2.181998,1.000000,1.303797,0.837494,1.000000,1.253165,0.792082,1.000000
17,ambitieux,ambitious,4.82,4.72,1.475000,1.330984,1,5.786517,1.377348,1.000000,...,0.987342,3.037975,1.996427,1.000000,1.645570,1.349625,1.000000,1.341772,1.060794,1.000000
18,amer,bitter,5.82,11.69,-1.700000,1.011328,1,4.704545,1.709736,0.988764,...,0.987342,1.051282,0.274332,0.987342,1.883117,1.701192,0.974684,3.089744,2.375119,0.987342
19,amical,friendly,4.26,11.22,1.887500,0.841845,1,4.738636,1.797152,0.988764,...,0.987342,4.833333,1.896111,0.987342,1.128205,0.518714,0.987342,1.012821,0.113228,0.987342
20,amusant,funny,25.24,13.04,2.025000,0.885538,1,4.522727,1.774515,0.988764,...,0.987342,5.551282,1.500194,0.987342,1.076923,0.419314,0.987342,1.012821,0.113228,0.987342
21,angoissé,anxious,0.28,2.57,-1.525000,1.067056,1,5.727273,1.428183,0.988764,...,0.987342,1.102564,0.381036,0.987342,5.576923,1.791170,0.987342,3.358974,2.150049,0.987342
22,animé,lively,2.79,3.18,1.275000,0.92743,1,4.404494,1.497870,1.000000,...,0.987342,3.782051,2.195908,0.987342,1.256410,0.728562,0.987342,1.076923,0.312893,0.987342
23,antipathique,obnoxious,0.96,1.55,-2.087500,1.081417,1,5.179775,1.534170,1.000000,...,0.987342,1.102564,0.413718,0.987342,2.115385,1.830341,0.987342,2.448718,2.080506,0.987342
24,anxieux,anxious,2.83,6.35,-1.437500,1.041466,1,5.719101,1.296751,1.000000,...,0.987342,1.038462,0.193552,0.987342,5.115385,1.960525,0.987342,2.987179,2.141086,0.987342
25,apaisant,soothing,0.70,2.30,1.925000,1.016011,1,4.181818,1.719031,0.988764,...,0.987342,4.217949,2.135947,0.987342,1.153846,0.560077,0.987342,1.064103,0.372417,0.987342
26,apathique,apathetic,0.46,0.41,-0.975000,1.252592,1,4.772727,1.616917,0.988764,...,0.987342,1.230769,0.881602,0.987342,1.705128,1.368561,0.987342,2.448718,1.911329,0.987342
27,appliqué,diligent,0.12,2.09,1.612500,0.878632,1,4.727273,1.792239,0.988764,...,1.000000,2.493671,1.845809,1.000000,1.392405,0.992507,1.000000,1.189873,0.556453,1.000000
28,arrangeant,accommodating,0.03,0.20,1.150000,0.994924,1,4.146067,1.556150,1.000000,...,1.000000,2.833333,1.847544,0.987342,1.303797,0.867570,1.000000,1.316456,1.006954,1.000000
29,arriéré,retarded,0.16,0.61,-1.800000,1.162712,1,5.314607,1.709569,1.000000,...,1.000000,1.265823,0.943383,1.000000,2.405063,1.984032,1.000000,3.164557,2.221286,1.000000
1032681,NaN,NaN,NaN,NaN,NaN,1.582939,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032682,NaN,NaN,NaN,NaN,NaN,1.218008,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032683,NaN,NaN,NaN,NaN,NaN,0.991658,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032684,NaN,NaN,NaN,NaN,NaN,0.90185,0.95,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032685,NaN,NaN,NaN,NaN,NaN,0.870672,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032686,NaN,NaN,NaN,NaN,NaN,1.155888,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032687,NaN,NaN,NaN,NaN,NaN,0.96489,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032688,NaN,NaN,NaN,NaN,NaN,0.801502,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032689,NaN,NaN,NaN,NaN,NaN,0.94668,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032690,NaN,NaN,NaN,NaN,NaN,0.953923,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032691,NaN,NaN,NaN,NaN,NaN,1.252592,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032692,NaN,NaN,NaN,NaN,NaN,1.177586,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032693,NaN,NaN,NaN,NaN,NaN,0.94668,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032694,NaN,NaN,NaN,NaN,NaN,1.028394,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032695,NaN,NaN,NaN,NaN,NaN,1.126142,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032696,NaN,NaN,NaN,NaN,NaN,1.028394,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032697,NaN,NaN,NaN,NaN,NaN,1.144538,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032698,NaN,NaN,NaN,NaN,NaN,1.333812,0.975,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032699,NaN,NaN,NaN,NaN,NaN,1.076504,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032700,NaN,NaN,NaN,NaN,NaN,1.386588,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032701,NaN,NaN,NaN,NaN,NaN,0.955994,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032702,NaN,NaN,NaN,NaN,NaN,1.188287,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032703,NaN,NaN,NaN,NaN,NaN,1.0185,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032704,NaN,NaN,NaN,NaN,NaN,0.925637,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032705,NaN,NaN,NaN,NaN,NaN,1.086162,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032706,NaN,NaN,NaN,NaN,NaN,0.927003,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032707,NaN,NaN,NaN,NaN,NaN,0.891237,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032708,NaN,NaN,NaN,NaN,NaN,0.962591,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032709,NaN,NaN,NaN,NaN,NaN,1.118812,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032710,NaN,NaN,NaN,NaN,NaN,3.371511,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN