# Trie des données pour récupération des Visages et des Mots

author = Alexandre Coumes

Trier les databases pour obtenir les ID des images de nos participants.

In [25]:
import pandas as pd

## Faces

### Loading of our data

Here we aim for the right sheet (Main Dataset) and create our subset

In [26]:
df = pd.read_excel("dataset.xlsx", sheet_name=1, header=7)
df.head()

,Model,EthnicitySelf,GenderSelf,AgeSelf,AgeRated,Unnamed: 5,FemaleProb,MaleProb,AsianProb,ChineseAsianProb,...,EyeSize,UpperHeadLength,MidfaceLength,ChinLength,ForeheadHeight,CheekboneHeight,CheekboneProminence,FaceRoundness,fWHR2,RaterN
0,NaN,NaN,NaN,NaN,R002_mean,R002_sd,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AF-200,A,F,NaN,32.571429,NaN,1.000000,0.000000,1.000000,NaN,...,0.060924,0.414099,0.326797,0.130719,0.264706,0.388189,91.5,0.545752,1.973890,28.0
2,AF-201,A,F,NaN,23.666667,NaN,1.000000,0.000000,0.962963,NaN,...,0.041892,0.414414,0.329279,0.144595,0.300901,0.383784,146.0,0.488288,2.068681,27.0
3,AF-202,A,F,NaN,24.448276,NaN,0.827586,0.172414,0.310345,NaN,...,0.051586,0.411080,0.310317,0.173424,0.298475,0.397029,58.0,0.481333,1.987261,29.0
4,AF-203,A,F,NaN,22.758621,NaN,1.000000,0.000000,0.758621,NaN,...,0.063913,0.354407,0.343793,0.169820,0.272266,0.421089,87.5,0.500231,1.902284,29.0

In [27]:
print(df.columns.tolist())

['Model', 'EthnicitySelf', 'GenderSelf', 'AgeSelf', 'AgeRated', 'Unnamed: 5', 'FemaleProb', 'MaleProb', 'AsianProb', 'ChineseAsianProb', 'JapaneseAsianProb', 'IndianAsianProb', 'OtherAsianProb', 'MiddleEasternProb', 'BlackProb', 'LatinoProb', 'MultiProb', 'OtherProb', 'WhiteProb', 'Afraid', 'Unnamed: 20', 'Angry', 'Unnamed: 22', 'Attractive', 'Unnamed: 24', 'Babyfaced', 'Unnamed: 26', 'Disgusted', 'Unnamed: 28', 'Dominant', 'Unnamed: 30', 'Feminine', 'Unnamed: 32', 'Happy', 'Unnamed: 34', 'Masculine', 'Unnamed: 36', 'Prototypic', 'Unnamed: 38', 'Sad', 'Unnamed: 40', 'Suitability', 'Unnamed: 42', 'Surprised', 'Unnamed: 44', 'Threatening', 'Unnamed: 46', 'Trustworthy', 'Unnamed: 48', 'Unusual', 'Unnamed: 50', 'Warm', 'Unnamed: 52', 'Competent', 'Unnamed: 54', 'SocialStatus', 'Unnamed: 56', 'LuminanceMedian', 'NoseWidth', 'NoseLength', 'LipThickness', 'FaceLength', 'EyeHeightR', 'EyeHeightL', 'EyeHeightAvg', 'EyeWidthR', 'EyeWidthL', 'EyeWidthAvg', 'FaceWidthCheeks', 'FaceWidthMouth', 'FaceWidthBZ', 'Forehead', 'UpperFaceLength2', 'PupilTopR', 'PupilTopL', 'PupilTopAsymmetry', 'PupilLipR', 'PupilLipL', 'PupilLipAvg', 'PupilLipAsymmetry', 'EyeDistance', 'BottomLipChin', 'MidcheekChinR', 'MidcheekChinL', 'CheeksAvg', 'MidbrowHairlineR', 'MidbrowHairlineL', 'MidbrowHairlineAvg', 'FaceColorRed', 'FaceColorGreen', 'FaceColorBlue', 'HairColorRed', 'HairColorGreen', 'HairColorBlue', 'HairLuminance', 'EyeLuminanceR', 'EyeLuminanceL', 'EyeBrowThicknessR', 'EyeBrowThicknessL', 'EyeBrowThicknessAvg', 'EyeLidThicknessR', 'EyeLidThicknessL', 'EyeLidThicknessAvg', 'FaceShape', 'Heartshapeness', 'NoseShape', 'LipFullness', 'EyeShape', 'EyeSize', 'UpperHeadLength', 'MidfaceLength', 'ChinLength', 'ForeheadHeight', 'CheekboneHeight', 'CheekboneProminence', 'FaceRoundness', 'fWHR2', 'RaterN']

In [32]:
df['Attractive'] = pd.to_numeric(df['Attractive'], errors='coerce')
df_attractivness = df.dropna(subset=['Attractive']) 
df_attractivness = df_attractivness.sort_values("Attractive", ascending=False)
df_attractivness.head()

,Model,EthnicitySelf,GenderSelf,AgeSelf,AgeRated,Unnamed: 5,FemaleProb,MaleProb,AsianProb,ChineseAsianProb,...,EyeSize,UpperHeadLength,MidfaceLength,ChinLength,ForeheadHeight,CheekboneHeight,CheekboneProminence,FaceRoundness,fWHR2,RaterN
485,WF-233,W,F,NaN,22.608696,NaN,1.0,0.0,0.000000,NaN,...,0.054667,0.413570,0.312014,0.163354,0.322602,0.367545,119.500000,0.378997,1.828704,23.0
198,BF-240,B,F,NaN,24.413793,NaN,1.0,0.0,0.000000,NaN,...,0.052414,0.368421,0.315355,0.144411,0.303828,0.379513,144.500000,0.438452,1.928230,29.0
356,LF-249,L,F,NaN,28.517241,NaN,1.0,0.0,0.068966,NaN,...,0.051197,0.402147,0.315235,0.165153,0.317300,0.378406,128.000000,0.417424,1.849013,29.0
191,BF-233,B,F,NaN,28.692308,NaN,1.0,0.0,0.000000,NaN,...,0.049060,0.387572,0.313369,0.152085,0.289657,0.388389,133.000000,0.415781,1.802247,26.0
435,WF-022,W,F,NaN,19.913978,NaN,1.0,0.0,0.000000,NaN,...,0.053637,0.372007,0.328729,0.180479,0.300875,0.432551,0.104972,0.538214,1.884346,92.0

> We create our Dataset of 60 faces, 30 of the most attractive and the less attractive.

In [33]:
df_attractivness = df_attractivness[['Model', 'Attractive', 'GenderSelf']]
df_top = df_attractivness.head(30)
df_bot = df_attractivness.tail(30)
df_final = pd.concat([df_top, df_bot])
df_final

      Model  Attractive GenderSelf
485  WF-233    5.478261          F
198  BF-240    5.310345          F
356  LF-249    5.241379          F
191  BF-233    5.120000          F
435  WF-022    5.086957          F
176  BF-218    5.080000          F
386  LM-224    5.071429          M
43   AF-242    4.964286          F
174  BF-216    4.892857          F
111  BF-002    4.892473          F
417  WF-003    4.890110          F
250  BM-043    4.852273          M
172  BF-214    4.846154          F
457  WF-205    4.826087          F
199  BF-241    4.821429          F
490  WF-238    4.800000          F
56   AF-255    4.800000          F
122  BF-013    4.777778          F
350  LF-243    4.769231          F
472  WF-220    4.758621          F
437  WF-024    4.755319          F
494  WF-242    4.750000          F
202  BF-244    4.750000          F
187  BF-229    4.730769          F
175  BF-217    4.714286          F
440  WF-027    4.685393          F
19   AF-218    4.678571          F
190  BF-232    4.666667          F
45   AF-244    4.666667          F
425  WF-012    4.663158          F
136  BF-029    2.116279          F
273  BM-219    2.111111          M
185  BF-227    2.111111          F
456  WF-204    2.107143          F
151  BF-044    2.106383          F
366  LM-203    2.090909          M
267  BM-213    2.080000          M
412  LM-251    2.080000          M
576  WM-236    2.038462          M
182  BF-224    2.034483          F
423  WF-010    2.011765          F
500  WF-248    2.000000          F
327  LF-220    2.000000          F
556  WM-215    1.892857          M
145  BF-038    1.892473          F
568  WM-228    1.888889          M
462  WF-210    1.884615          F
89   AM-233    1.857143          M
69   AM-212    1.846154          M
82   AM-226    1.809524          M
547  WM-206    1.806452          M
371  LM-209    1.785714          M
116  BF-007    1.769231          F
542  WM-201    1.727273          M
439  WF-026    1.721649          F
502  WF-250    1.720000          F
416  WF-002    1.612903          F
158  BF-200    1.551724          F
402  LM-240    1.541667          M
80   AM-224    1.520000          M

## Words

In [45]:
df_word = pd.read_excel("dataset_words.xlsx", nrows=525)
df_word.head()

,Trait,Translation,FreqMovies,FreqBooks,MeanVal,SDVal,RateVal,MeanPCONS,SDPCONS,RatePCONS,...,RateDisgust,MeanHappinessjoie,SDHappiness,RateHappiness,MeanFear,SDFear,RateFear,MeanSadness,SDSadness,RateSadness
0,accessible,approachable,1.49,4.12,1.443038,1.094823,0.9875,4.191011,1.608757,1.0,...,1.0,2.860759,2.055226,1.0,1.253165,0.759020,1.0,1.051282,0.222000,0.987342
1,accueillant,welcoming,1.21,1.82,2.137500,0.807304,1.0000,4.191011,1.724663,1.0,...,1.0,4.873418,1.814239,1.0,1.113924,0.480047,1.0,1.025316,0.158088,1.000000
2,actif,active,4.12,3.58,1.900000,0.820620,1.0000,5.000000,1.644550,1.0,...,1.0,3.594937,2.060116,1.0,1.265823,0.728695,1.0,1.139241,0.614654,1.000000
3,admirable,admirable,6.02,23.92,2.187500,0.994844,1.0000,4.483146,1.834718,1.0,...,1.0,4.379747,2.114079,1.0,1.164557,0.649070,1.0,1.063291,0.333658,1.000000
4,admiratif,appreciative,0.26,2.57,0.800000,1.173548,1.0000,4.876404,1.643308,1.0,...,1.0,3.582278,2.029321,1.0,1.291139,0.907969,1.0,1.202532,0.806699,1.000000

In [47]:
df_word.columns

Index(['Trait', 'Translation', 'FreqMovies', 'FreqBooks', ' MeanVal', 'SDVal',
       'RateVal', 'MeanPCONS', 'SDPCONS', 'RatePCONS', 'MeanOCONS', 'SDOCONS',
       'RateOCONS', 'MeanApp', 'SDApp', 'RateApp', 'MeanAnger', 'SDAnger',
       'RateAnger', 'MeanDisgust', 'SDDisgust', 'RateDisgust',
       'MeanHappinessjoie', 'SDHappiness', 'RateHappiness', 'MeanFear',
       'SDFear', 'RateFear', 'MeanSadness', 'SDSadness', 'RateSadness'],
      dtype='str')

In [48]:

df_word = df_word.sort_values(by=" MeanVal", ascending=True)
df_word_top = df_word.head(30); df_word_bot = df_word.tail(30)
df_word_final = pd.concat([df_word_top, df_word_bot])

In [50]:
df_word_final = df_word_final[['Trait', ' MeanVal']]
df_word_final

             Trait   MeanVal
410        raciste -2.700000
248        ignoble -2.687500
316     malhonnête -2.600000
166        égoïste -2.562500
234        haineux -2.512500
334      méprisant -2.487500
296  irrespectueux -2.462500
520        violent -2.462500
327        méchant -2.450000
362         odieux -2.400000
121      dégoûtant -2.387500
111          cruel -2.375000
126   démoralisant -2.337500
276        injuste -2.325000
128      déprimant -2.312500
283      insultant -2.312500
246      hypocrite -2.300000
289     intolérant -2.287500
132    désagréable -2.262500
333        menteur -2.262500
445        sadique -2.225000
60          brutal -2.212500
326        mauvais -2.212500
259       inamical -2.202532
347      mythomane -2.187500
513        vicieux -2.175000
297  irresponsable -2.162500
329       médisant -2.137500
133      désespéré -2.125000
218        furieux -2.125000
5         adorable  2.137500
462       sociable  2.137500
273      ingénieux  2.139241
206         fidèle  2.150000
55             bon  2.150000
112        cultivé  2.162500
39     attentionné  2.162500
3        admirable  2.187500
434    responsable  2.212500
151           doué  2.225000
70      chaleureux  2.225000
54    bienveillant  2.237500
371         ouvert  2.250000
238        heureux  2.250000
198      fascinant  2.262500
396        positif  2.262500
460        sincère  2.287500
433    respectueux  2.287500
286    intelligent  2.300000
239        honnête  2.300000
303          juste  2.312500
59        brillant  2.312500
499       tolérant  2.337500
155          drôle  2.337500
488     talentueux  2.362500
223       généreux  2.362500
287    intéressant  2.425000
224         génial  2.475000
211     formidable  2.487500
335    merveilleux  2.500000